### ISSUE TITLE
Wavelength Scale

### ISSUE THREAD

**Issue by clidman** [daniel-muthukrishna/DASH#18]
- Add a wavelength scale to the horizontal axis on the lower plot
- Display rest wavelengths and observer wavelengths
- Add a quit button to the GUI

**Comment by daniel-muthukrishna** [comment]
Done.
Quit button added. Both observed and rest wavelength axes have been added. The rest wavelength scales with the plotting redshift. 
I've also added a vertical slider bar on the cross-correlation plot, which lets you change the plotted redshift.

Please feel free to leave more issues

Cheers.
